from app.main.lib.es_indexer_base import ESIndexerBase


class ESIndexerTest(ESIndexerBase):
    """
    Unit Test Indexer class
    """

    def __init__(self, name):
        super().__init__(name)

    def get_es_mapping_fields(self):
        return {
            'id': {"type": "keyword"},
            'person_logic_id': {"type": "keyword"},
            'person_id': {"type": "keyword"},
            'person_name': {"type": "keyword"},
            'person_name_before': {"type": "keyword"},
            'gender': {"type": "keyword"},
            'gender_name': {"type": "keyword"},
            'birthday': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'phone': {"type": "keyword"},
            'nation': {"type": "keyword"},
            'nation_name': {"type": "keyword"},
            'marriage_status': {"type": "keyword"},
            'marriage_status_name': {"type": "keyword"},
            'degree_of_education': {"type": "keyword"},
            'degree_of_education_name': {"type": "keyword"},
            'height': {"type": "keyword"},
            'native_place': {"type": "keyword"},
            'political_outlook': {"type": "keyword"},
            'political_outlook_name': {"type": "keyword"},
            'religious_belief': {"type": "keyword"},
            'religious_belief_name': {"type": "keyword"},
            'career_type': {"type": "keyword"},
            'career_type_name': {"type": "keyword"},
            'career': {"type": "keyword"},
            'career_name': {"type": "keyword"},
            'ad_logic_id': {"type": "keyword"},
            # 'register_address': {"type": "text",
                                 # "analyzer": "ik_smart"},
            'register_address_detail': {"type": "keyword"},
            'register_address_logic_id': {"type": "keyword"},
            'person_house_relation_logic_id': {"type": "keyword"},
            'relation_type': {"type": "keyword"},
            'relation_type_name': {"type": "keyword"},
            'house_logic_id': {"type": "keyword"},
            'live_address': {"type": "keyword"},
            'live_address_detail': {"type": "keyword"},
            'live_address_logic_id': {"type": "keyword"},
            'job_address_detail': {"type": "keyword"},
            'job_address_logic_id': {"type": "keyword"},
            'create_user': {"type": "keyword"},
            'update_user': {"type": "keyword"},
            'create_time': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'update_time': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'person_company_relation_logic_id': {"type": "keyword"},
            'company_logic_id': {"type": "keyword"},
            'block_logic_id': {"type": "keyword"},
            'platoon_building_logic_id': {"type": "keyword"},
            'unit_logic_id': {"type": "keyword"},
            'file_logic_id': {"type": "keyword"},
            'file_object_type': {"type": "keyword"},
            'file_object_type_name': {"type": "keyword"},
            'file_object_id': {"type": "keyword"},
            'file_type': {"type": "keyword"},
            'file_type_name': {"type": "keyword"},
            'file_name': {"type": "keyword"},
            'file_path': {"type": "keyword"},
            'data_source': {"type": "keyword"},
            'consistent_identification': {"type": "keyword"},
            'consistent_identification_name': {"type": "keyword"},
            'id_card_type': {"type": "keyword"},
            'id_card_type_name': {"type": "keyword"},
            'registered_person_flag': {"type": "keyword"},
            'hukou_code': {"type": "keyword"},
            'householder_id': {"type": "keyword"},
            'registered_person_type_code': {"type": "keyword"},
            'registered_person_type_name': {"type": "keyword"},
            'floating_person_flag': {"type": "keyword"},
            'inflow_reason': {"type": "keyword"},
            'inflow_reason_name': {"type": "keyword"},
            'floating_person_card_code': {"type": "keyword"},
            'registration_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'floating_due_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'residence_type': {"type": "keyword"},
            'residence_type_name': {"type": "keyword"},
            'focus_person_flg': {"type": "long"},
            'health_status': {"type": "keyword"},
            'health_status_name': {"type": "keyword"},
            'rear_person_flag': {"type": "keyword"},
            'annual_personal_income': {"type": "keyword"},
            'rear_person_type': {"type": "keyword"},
            'rear_person_type_name': {"type": "keyword"},
            'primary_member_id': {"type": "keyword"},
            'primary_member_name': {"type": "keyword"},
            'primary_member_health_status': {"type": "keyword"},
            'primary_member_health_status_name': {"type": "keyword"},
            'relationship_with_rear': {"type": "keyword"},
            'relationship_with_rear_name': {"type": "keyword"},
            'primary_member_phone': {"type": "keyword"},
            'primary_member_work_address': {"type": "keyword"},
            'annual_family_income': {"type": "keyword"},
            'difficulties_and_demands': {"type": "keyword"},
            'has_del': {"type": "byte"},
            'foreigner_flag': {"type": "keyword"},
            'foreign_surname': {"type": "keyword"},
            'foreign_name': {"type": "keyword"},
            'chinese_name': {"type": "keyword"},
            'nationality': {"type": "keyword"},
            'country_name': {"type": "keyword"},
            'foreigners_card_code': {"type": "keyword"},
            'foreigners_due_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'reason_to_china': {"type": "keyword"},
            'reason_to_china_name': {"type": "keyword"},
            'company_name': {"type": "keyword"},
            'arrival_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'estimated_departure_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'release_person_flag': {"type": "keyword"},
            'recidivism_flag': {"type": "keyword"},
            'original_sin': {"type": "keyword"},
            'original_sin_name': {"type": "keyword"},
            'original_sentence': {"type": "keyword"},
            'place_of_sentence': {"type": "keyword"},
            'release_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'risk_assessment_type': {"type": "keyword"},
            'risk_assessment_name': {"type": "keyword"},
            'connection_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'connection_situation': {"type": "keyword"},
            'connection_situation_name': {"type": "keyword"},
            'placement_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'placement_situation': {"type": "keyword"},
            'placement_situation_name': {"type": "keyword"},
            'reason_for_non_placement': {"type": "keyword"},
            'release_help_situation': {"type": "keyword"},
            'release_help_situation_name': {"type": "keyword"},
            'crime_again_flag': {"type": "keyword"},
            'recidivism_sin': {"type": "keyword"},
            'recidivism_sin_name': {"type": "keyword"},
            'community_correction_person_flag': {"type": "keyword"},
            'original_detention_place': {"type": "keyword"},
            'correction_type': {"type": "keyword"},
            'correction_type_name': {"type": "keyword"},
            'correction_person_sin_type': {"type": "keyword"},
            'correction_person_sin_detailed': {"type": "keyword"},
            'correction_person_original_sentence': {"type": "keyword"},
            'original_sentence_start_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'original_sentence_end_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'correction_start_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'correction_end_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            'receiving_type': {"type": "keyword"},
            'receiving_type_name': {"type": "keyword"},
            'four_histories': {"type": "keyword"},
            'four_histories_name': {"type": "keyword"},
            'three_involved': {"type": "keyword"},
            'three_involved_name': {"type": "keyword"},
            'has_correction_group': {"type": "keyword"},
            'correction_group_type': {"type": "keyword"},
            'correction_group_type_name': {"type": "keyword"},
            'correction_release_type': {"type": "keyword"},
            'correction_release_type_name': {"type": "keyword"},
            'escape_control_flag': {"type": "keyword"},
            'reason_escape_control': {"type": "keyword"},
            'supervision_escape_control': {"type": "keyword"},
            'correction_escape_control': {"type": "keyword"},
            # 'leakage_flag': {"type": "keyword"},
            # 'reason_leakage': {"type": "keyword"},
            # 'supervision_leakage': {"type": "keyword"},
            # 'correction_leakage': {"type": "keyword"},
            # 'rewards_punishments': {"type": "keyword"},
            # 'penalty_change': {"type": "keyword"},
            # 'severe_mental_disorders_person_flag': {"type": "keyword"},
            # 'family_economic_status': {"type": "keyword"},
            # 'subsistence_allowance_flag': {"type": "keyword"},
            # 'guardian_id': {"type": "keyword"},
            # 'guardian_name': {"type": "keyword"},
            # 'guardian_phone': {"type": "keyword"},
            # 'first_onset_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            # 'current_diagnostic_type': {"type": "keyword"},
            # 'current_diagnostic_type_name': {"type": "keyword"},
            # 'trouble_flag': {"type": "keyword"},
            # 'trouble_cnt': {"type": "keyword"},
            # 'last_trouble_date': {"type": "date", "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},
            # 'current_danger_level': {"type": "keyword"},
            # 'current_danger_level_name': {"type": "keyword"},
            # 'treatment_situation': {"type": "keyword"},
            # 'treatment_situation_name': {"type": "keyword"},
            # 'treatment_hospital': {"type": "keyword"},
            # 'hospitalized_reason': {"type": "keyword"},
            # 'hospitalized_reason_name': {"type": "keyword"},
            # 'rehabilitation_training_institutions': {"type": "keyword"},
            # 'participating_managers': {"type": "keyword"},
            # 'participating_managers_name': {"type": "keyword"},
            # 'found_first_date': {"type": "keyword"},
            # 'control_situation': {"type": "keyword"},
            # 'control_situation_name': {"type": "keyword"},
            # 'drug_addict_flag': {"type": "keyword"},
            # 'controller_name': {"type": "keyword"},
            # 'controller_phone': {"type": "keyword"},
            # 'drug_addict_helper_name': {"type": "keyword"},
            # 'drug_addict_helper_phone': {"type": "keyword"},
            # 'drug_addict_crime_flag': {"type": "keyword"},
            # 'drug_addict_crime_situation': {"type": "keyword"},
            # 'drug_reason': {"type": "keyword"},
            # 'drug_result': {"type": "keyword"},
            # 'AIDS_risk_person_flag': {"type": "keyword"},
            # 'infection_route': {"type": "keyword"},
            # 'infection_route_name': {"type": "keyword"},
            # 'aids_crime_flag': {"type": "keyword"},
            # 'aids_crime_situation': {"type": "keyword"},
            # 'aids_sin_type': {"type": "keyword"},
            # 'degree_concern': {"type": "keyword"},
            # 'degree_concern_name': {"type": "keyword"},
            # 'receiving_cure_situation': {"type": "keyword"},
            # 'receiving_cure_situation_name': {"type": "keyword"},
            # 'receiving_cure_institution': {"type": "keyword"},
            # 'AIDS_help_situation': {"type": "keyword"},
            # 'AIDS_helper_name': {"type": "keyword"},
            # 'AIDS_helper_phone': {"type": "keyword"},
            # 'key_teenagers_flag': {"type": "keyword"},
            # 'teenagers_type': {"type": "keyword"},
            # 'teenagers_type_name': {"type": "keyword"},
            # 'family_situation': {"type": "keyword"},
            # 'family_situation_name': {"type": "keyword"},
            # 'guardian_relationship': {"type": "keyword"},
            # 'guardian_relationship_name': {"type": "keyword"},
            # 'guardian_address': {"type": "keyword"},
            # 'teenagers_help_situation': {"type": "keyword"},
            # 'teenagers_help_method': {"type": "keyword"},
            # 'teenagers_helper_name': {"type": "keyword"},
            # 'teenagers_helper_phone': {"type": "keyword"},
            # 'address_detail': {"type": "keyword"},
            # 'address_name': {"type": "keyword"},
            # 'address_element_type': {"type": "keyword"},
            # 'address_element_name': {"type": "keyword"},
            # 'province_code': {"type": "keyword"},
            # 'city_code': {"type": "keyword"},
            # 'county_district_code': {"type": "keyword"},
            # 'town_code': {"type": "keyword"},
            # 'community_village_code': {"type": "keyword"},
            # 'grid_code': {"type": "keyword"},
            # 'road_name': {"type": "keyword"},
            # 'road_child_name': {"type": "keyword"},
            # 'community_name': {"type": "keyword"},
            # 'house_floor': {"type": "keyword"},
            # 'house_no': {"type": "keyword"},
            'longitude': {"type": "keyword"},
            'latitude': {"type": "keyword"},
            # 'order_flag': {"type": "long"}
        }
