"""empty message

Revision ID: c21088325dab
Revises: dc339d16cfcc
Create Date: 2023-04-02 16:09:54.493698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21088325dab'
down_revision = 'dc339d16cfcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_dict',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('dict_logic_id', sa.String(length=60), nullable=False, comment='逻辑主键'),
    sa.Column('tag_name', sa.String(length=100), nullable=False, comment='标签名'),
    sa.Column('tag_code', sa.String(length=45), nullable=False, comment='数据值'),
    sa.Column('tag_type_code', sa.String(length=45), nullable=False, comment='类型代码'),
    sa.Column('tag_type_name', sa.String(length=45), nullable=False, comment='类型名称'),
    sa.Column('order_num', sa.Integer(), nullable=False, comment='排序（升序）'),
    sa.Column('parent_code', sa.String(length=45), nullable=False, comment='父级编号'),
    sa.Column('remarks', sa.String(length=255), nullable=False, comment='备注信息'),
    sa.Column('has_del', sa.String(length=45), nullable=False, comment='数据值'),
    sa.Column('create_user', sa.String(length=100), nullable=False, comment='创建者账号'),
    sa.Column('update_user', sa.String(length=100), nullable=False, comment='更新者账号'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_dict')
    # ### end Alembic commands ###
