from flask_restx import Namespace, fields
from app.main.dto import return_value_dto
from app.main.enum.field_type_enum import FieldTypeEnum
from app.main.enum.filter_type_enum import FilterTypeEnum


class PersonInfoDTO(object):
    """
    实有人口信息
    """
    api = Namespace('实有人口信息', description='实有人口信息查询、修改')
    return_value = return_value_dto(api)

    person_info_delete = api.model('Person_Info_Delete', {
        'data': fields.List(fields.String(required=True, description='主键id')
                            )})
    # person_info_input = api.model("Person_Info_Input", {
    #     'data': fields.List(fields.Nested(person_info, required=True, description='实有人口明细'))})
    person_info = api.model('Person_Info', {
        'id': fields.String(required=False, description='主键id'),
        'person_logic_id': fields.String(required=False, description='逻辑主键'),
        'person_id': fields.String(required=False, description='公民身份号码'),
        'person_name': fields.String(required=False, description='姓名'),
        'person_name_before': fields.String(required=False, description='曾用名'),
        'gender': fields.String(required=False, description='性别 1-男，2-女'),
        'gender_name': fields.String(required=False, description='性别名称'),
        'birthday': fields.String(required=False, description='生日'),
        'phone': fields.String(required=False, description='手机号'),
        'nation': fields.String(required=False, description='民族'),
        'nation_name': fields.String(required=False, description='民族名称'),
        'marriage_status': fields.String(required=False, description='婚姻状况'),
        'marriage_status_name': fields.String(required=False, description=''),
        'degree_of_education': fields.String(required=False, description=''),
        'degree_of_education_name': fields.String(required=False, description=''),
        'height': fields.String(required=False, description=''),
        'native_place': fields.String(required=False, description=''),
        'political_outlook': fields.String(required=False, description=''),
        'political_outlook_name': fields.String(required=False, description=''),
        'religious_belief': fields.String(required=False, description=''),
        'religious_belief_name': fields.String(required=False, description=''),
        'career_type': fields.String(required=False, description=''),
        'career_type_name': fields.String(required=False, description=''),
        'career': fields.String(required=False, description=''),
        'career_name': fields.String(required=False, description=''),
        'ad_logic_id': fields.String(required=False, description=''),
        'register_address': fields.String(required=False, description=''),
        'register_address_detail': fields.String(required=False, description=''),
        'register_address_logic_id': fields.String(required=False, description=''),
        'person_house_relation_logic_id': fields.String(required=False, description=''),
        'relation_type': fields.String(required=False, description=''),
        'relation_type_name': fields.String(required=False, description=''),
        'house_logic_id': fields.String(required=False, description=''),
        'live_address': fields.String(required=False, description=''),
        'live_address_detail': fields.String(required=False, description=''),
        'live_address_logic_id': fields.String(required=False, description=''),
        'job_address_detail': fields.String(required=False, description=''),
        'job_address_logic_id': fields.String(required=False, description=''),
        'create_user': fields.String(required=False, description=''),
        'update_user': fields.String(required=False, description=''),
        'create_time': fields.String(required=False, description=''),
        'update_time': fields.String(required=False, description=''),
        'person_company_relation_logic_id': fields.String(required=False, description=''),
        'company_logic_id': fields.String(required=False, description=''),
        'block_logic_id': fields.String(required=False, description=''),
        'platoon_building_logic_id': fields.String(required=False, description=''),
        'unit_logic_id': fields.String(required=False, description=''),
        'file_logic_id': fields.String(required=False, description=''),
        'file_object_type': fields.String(required=False, description=''),
        'file_object_type_name': fields.String(required=False, description=''),
        'file_object_id': fields.String(required=False, description=''),
        'file_type': fields.String(required=False, description=''),
        'file_type_name': fields.String(required=False, description=''),
        'file_name': fields.String(required=False, description=''),
        'file_path': fields.String(required=False, description=''),
        'data_source': fields.String(required=False, description=''),
        'consistent_identification': fields.String(required=False, description=''),
        'consistent_identification_name': fields.String(required=False, description=''),
        'id_card_type': fields.String(required=False, description=''),
        'id_card_type_name': fields.String(required=False, description=''),
        'registered_person_flag': fields.String(required=False, description=''),
        'hukou_code': fields.String(required=False, description=''),
        'householder_id': fields.String(required=False, description=''),
        'registered_person_type_code': fields.String(required=False, description=''),
        'registered_person_type_name': fields.String(required=False, description=''),
        'floating_person_flag': fields.String(required=False, description=''),
        'inflow_reason': fields.String(required=False, description=''),
        'inflow_reason_name': fields.String(required=False, description=''),
        'floating_person_card_code': fields.String(required=False, description=''),
        'registration_date': fields.String(required=False, description=''),
        'floating_due_date': fields.String(required=False, description=''),
        'residence_type': fields.String(required=False, description=''),
        'residence_type_name': fields.String(required=False, description=''),
        'focus_person_flg': fields.String(required=False, description=''),
        'health_status': fields.String(required=False, description=''),
        'health_status_name': fields.String(required=False, description=''),
        'rear_person_flag': fields.String(required=False, description=''),
        'annual_personal_income': fields.String(required=False, description=''),
        'rear_person_type': fields.String(required=False, description=''),
        'rear_person_type_name': fields.String(required=False, description=''),
        'primary_member_id': fields.String(required=False, description=''),
        'primary_member_name': fields.String(required=False, description=''),
        'primary_member_health_status': fields.String(required=False, description=''),
        'primary_member_health_status_name': fields.String(required=False, description=''),
        'relationship_with_rear': fields.String(required=False, description=''),
        'relationship_with_rear_name': fields.String(required=False, description=''),
        'primary_member_phone': fields.String(required=False, description=''),
        'primary_member_work_address': fields.String(required=False, description=''),
        'annual_family_income': fields.String(required=False, description=''),
        'difficulties_and_demands': fields.String(required=False, description=''),
        'has_del': fields.String(required=False, description=''),
        'foreigner_flag': fields.String(required=False, description=''),
        'foreign_surname': fields.String(required=False, description=''),
        'foreign_name': fields.String(required=False, description=''),
        'chinese_name': fields.String(required=False, description=''),
        'nationality': fields.String(required=False, description=''),
        'country_name': fields.String(required=False, description=''),
        'foreigners_card_code': fields.String(required=False, description=''),
        'foreigners_due_date': fields.String(required=False, description=''),
        'reason_to_china': fields.String(required=False, description=''),
        'reason_to_china_name': fields.String(required=False, description=''),
        'company_name': fields.String(required=False, description=''),
        'arrival_date': fields.String(required=False, description=''),
        'estimated_departure_date': fields.String(required=False, description=''),
        'release_person_flag': fields.String(required=False, description=''),
        'recidivism_flag': fields.String(required=False, description=''),
        'original_sin': fields.String(required=False, description=''),
        'original_sin_name': fields.String(required=False, description=''),
        'original_sentence': fields.String(required=False, description=''),
        'place_of_sentence': fields.String(required=False, description=''),
        'release_date': fields.String(required=False, description=''),
        'risk_assessment_type': fields.String(required=False, description=''),
        'risk_assessment_name': fields.String(required=False, description=''),
        'connection_date': fields.String(required=False, description=''),
        'connection_situation': fields.String(required=False, description=''),
        'connection_situation_name': fields.String(required=False, description=''),
        'placement_date': fields.String(required=False, description=''),
        'placement_situation': fields.String(required=False, description=''),
        'placement_situation_name': fields.String(required=False, description=''),
        'reason_for_non_placement': fields.String(required=False, description=''),
        'release_help_situation': fields.String(required=False, description=''),
        'release_help_situation_name': fields.String(required=False, description=''),
        'crime_again_flag': fields.String(required=False, description=''),
        'recidivism_sin': fields.String(required=False, description=''),
        'recidivism_sin_name': fields.String(required=False, description=''),
        'community_correction_person_flag': fields.String(required=False, description=''),
        'original_detention_place': fields.String(required=False, description=''),
        'correction_type': fields.String(required=False, description=''),
        'correction_type_name': fields.String(required=False, description=''),
        'correction_person_sin_type': fields.String(required=False, description=''),
        'correction_person_sin_detailed': fields.String(required=False, description=''),
        'correction_person_original_sentence': fields.String(required=False, description=''),
        'original_sentence_start_date': fields.String(required=False, description=''),
        'original_sentence_end_date': fields.String(required=False, description=''),
        'correction_start_date': fields.String(required=False, description=''),
        'correction_end_date': fields.String(required=False, description=''),
        'receiving_type': fields.String(required=False, description=''),
        'receiving_type_name': fields.String(required=False, description=''),
        'four_histories': fields.String(required=False, description=''),
        'four_histories_name': fields.String(required=False, description=''),
        'three_involved': fields.String(required=False, description=''),
        'three_involved_name': fields.String(required=False, description=''),
        'has_correction_group': fields.String(required=False, description=''),
        'correction_group_type': fields.String(required=False, description=''),
        'correction_group_type_name': fields.String(required=False, description=''),
        'correction_release_type': fields.String(required=False, description=''),
        'correction_release_type_name': fields.String(required=False, description=''),
        'escape_control_flag': fields.String(required=False, description=''),
        'reason_escape_control': fields.String(required=False, description=''),
        'supervision_escape_control': fields.String(required=False, description=''),
        'correction_escape_control': fields.String(required=False, description=''),
        'leakage_flag': fields.String(required=False, description=''),
        'reason_leakage': fields.String(required=False, description=''),
        'supervision_leakage': fields.String(required=False, description=''),
        'correction_leakage': fields.String(required=False, description=''),
        'rewards_punishments': fields.String(required=False, description=''),
        'penalty_change': fields.String(required=False, description=''),
        'severe_mental_disorders_person_flag': fields.String(required=False, description=''),
        'family_economic_status': fields.String(required=False, description=''),
        'subsistence_allowance_flag': fields.String(required=False, description=''),
        'guardian_id': fields.String(required=False, description=''),
        'guardian_name': fields.String(required=False, description=''),
        'guardian_phone': fields.String(required=False, description=''),
        'first_onset_date': fields.String(required=False, description=''),
        'current_diagnostic_type': fields.String(required=False, description=''),
        'current_diagnostic_type_name': fields.String(required=False, description=''),
        'trouble_flag': fields.String(required=False, description=''),
        'trouble_cnt': fields.String(required=False, description=''),
        'last_trouble_date': fields.String(required=False, description=''),
        'current_danger_level': fields.String(required=False, description=''),
        'current_danger_level_name': fields.String(required=False, description=''),
        'treatment_situation': fields.String(required=False, description=''),
        'treatment_situation_name': fields.String(required=False, description=''),
        'treatment_hospital': fields.String(required=False, description=''),
        'hospitalized_reason': fields.String(required=False, description=''),
        'hospitalized_reason_name': fields.String(required=False, description=''),
        'rehabilitation_training_institutions': fields.String(required=False, description=''),
        'participating_managers': fields.String(required=False, description=''),
        'participating_managers_name': fields.String(required=False, description=''),
        'found_first_date': fields.String(required=False, description=''),
        'control_situation': fields.String(required=False, description=''),
        'control_situation_name': fields.String(required=False, description=''),
        'drug_addict_flag': fields.String(required=False, description=''),
        'controller_name': fields.String(required=False, description=''),
        'controller_phone': fields.String(required=False, description=''),
        'drug_addict_helper_name': fields.String(required=False, description=''),
        'drug_addict_helper_phone': fields.String(required=False, description=''),
        'drug_addict_crime_flag': fields.String(required=False, description=''),
        'drug_addict_crime_situation': fields.String(required=False, description=''),
        'drug_reason': fields.String(required=False, description=''),
        'drug_result': fields.String(required=False, description=''),
        'AIDS_risk_person_flag': fields.String(required=False, description=''),
        'infection_route': fields.String(required=False, description=''),
        'infection_route_name': fields.String(required=False, description=''),
        'aids_crime_flag': fields.String(required=False, description=''),
        'aids_crime_situation': fields.String(required=False, description=''),
        'aids_sin_type': fields.String(required=False, description=''),
        'degree_concern': fields.String(required=False, description=''),
        'degree_concern_name': fields.String(required=False, description=''),
        'receiving_cure_situation': fields.String(required=False, description=''),
        'receiving_cure_situation_name': fields.String(required=False, description=''),
        'receiving_cure_institution': fields.String(required=False, description=''),
        'AIDS_help_situation': fields.String(required=False, description=''),
        'AIDS_helper_name': fields.String(required=False, description=''),
        'AIDS_helper_phone': fields.String(required=False, description=''),
        'key_teenagers_flag': fields.String(required=False, description=''),
        'teenagers_type': fields.String(required=False, description=''),
        'teenagers_type_name': fields.String(required=False, description=''),
        'family_situation': fields.String(required=False, description=''),
        'family_situation_name': fields.String(required=False, description=''),
        'guardian_relationship': fields.String(required=False, description=''),
        'guardian_relationship_name': fields.String(required=False, description=''),
        'guardian_address': fields.String(required=False, description=''),
        'teenagers_help_situation': fields.String(required=False, description=''),
        'teenagers_help_method': fields.String(required=False, description=''),
        'teenagers_helper_name': fields.String(required=False, description=''),
        'teenagers_helper_phone': fields.String(required=False, description=''),
        'address_detail': fields.String(required=False, description=''),
        'address_name': fields.String(required=False, description=''),
        'address_element_type': fields.String(required=False, description=''),
        'address_element_name': fields.String(required=False, description=''),
        'province_code': fields.String(required=False, description=''),
        'city_code': fields.String(required=False, description=''),
        'county_district_code': fields.String(required=False, description=''),
        'town_code': fields.String(required=False, description=''),
        'community_village_code': fields.String(required=False, description=''),
        'grid_code': fields.String(required=False, description=''),
        'road_name': fields.String(required=False, description=''),
        'road_child_name': fields.String(required=False, description=''),
        'community_name': fields.String(required=False, description=''),
        'house_floor': fields.String(required=False, description=''),
        'house_no': fields.String(required=False, description=''),
        'longitude': fields.String(required=False, description=''),
        'latitude': fields.String(required=False, description=''),
        'order_flag': fields.String(required=False, description='')

    })
    query_setting = {
        "id": {
            "filter_type": FilterTypeEnum.MUST.name,
            "filed_type": FieldTypeEnum.LIST.name
        },}
    query_conditions = {
        # "value": '搜索数据值',
        'eachPage': '每页条数',
        'currentPage': '当前页数',
        'sortBy': '排序字段',
        'sortDirection': '升序：asc，降序：desc'
    }

    person_info_input = api.model("Person_Info_Input", {
        'data': fields.List(fields.Nested(person_info, required=True, description='实有人口明细'))})

    query_fields = {'id': '记录id',
                    'person_logic_id': '逻辑主键',
                    'person_id': '公民身份号码',
                    'person_name': '姓名',
                    'person_name_before': '曾用名',
                    'gender': '性别 1-男，2-女',
                    'gender_name': '性别名称',
                    'birthday': '生日',
                    'phone': '手机号',
                    'nation': '民族',
                    'nation_name': '民族名称',
                    'marriage_status': '婚姻状况'}
