version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es-test
    environment:
      - node.name=es01
      - cluster.name=es-test
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers="X-Requested-With, Content-Type, Content-Length, X-User"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports:
      - 19200:9200
    networks:
      - elastic

  kibana:
      image: docker.elastic.co/kibana/kibana:7.17.7
      container_name: kibana-test
      #volumes:
      #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      environment:
        SERVER_NAME: kibana.matthew.org
        ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
      - elastic
      ports:
        - 15601:5601


volumes:
  data01:
    driver: local


networks:
  elastic:
    driver: bridge
